### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by aminalhazwani** [bwinton/DesignSystem#25]
We internally agreed that we are building a Design System and not a Style Guide. Can we rename the repository accordingly? We should also align on how we name the repository under Firefox UX. Sometimes we use camel case other times we use hyphens. Personally I prefer all lowercase with hyphens 💯

**Comment by aminalhazwani** [comment]
Anyone? 😄

**Comment by bwinton** [comment]
This is going to be the last thing we do, just before we merge it to the FirefoxUX org.

To highlight the importance of, and to maintain consistency with the DesignValues and the SharedBanner, I think keeping CamelCase for the repo/project level is a good idea.

**Comment by aminalhazwani** [comment]
Thank you @bwinton, I will re-label this issue as low priority.

**Comment by bwinton** [comment]
It's still high priority I think, but it's just going to not be done for a while.  :)

**Comment by bwinton** [comment]
Fixed by 919c114a5e94344bcd3589f90c8144a3f0c4849f, I believe.
