### ISSUE TITLE
Display content structure in the url

### ISSUE THREAD

**Issue by brassy-** [bwinton/DesignSystem#39]
We should display the content hierarchy in the URL structure.

I expect to have as final results something like
**.../style/colors.html** instead of **.../colors.html**

Could be nice to place the specific HTML files inside their parent folder (in our example **style** is the folder, **colors.html** is the file inside the folder). I believe this would be helpful for our content creators and editors in the next future.

**Comment by bwinton** [comment]
So, if we do this, people will expect there to be something at **…/style/** (or **…/style/index.html**) too.  Do we have enough content to make pages for each of those categories?

**Comment by brassy-** [comment]
Hey @bwinton, any news on this one? With more content on the product, we need it more and more.

**Comment by bwinton** [comment]
Nope, but I could probably do it today…
