### ISSUE TITLE
old links are broken

### ISSUE THREAD

**Issue by designakt** [bwinton/DesignSystem#55]
links used to access the Design System are broken since renaming it to DesignSystem

these result in a 404:
https://bwinton.github.io/StyleGuide/#/welcome
https://bwinton.github.io/StyleGuide/

**Comment by bwinton** [comment]
Yeah, you need to update your links.  (I fixed all the ones I could find in the repo, but if there are some missing, please let me know where they are!

**Comment by designakt** [comment]
I was more concerned with links not in our control. Bookmarks people made, or other ways someone saved a link. Is there a way to do a forward from any StyleGuide URL to the same URL containing DesignSystem?
(Not sure how much effort that would be or how many people would be affected currently.)

**Comment by bwinton** [comment]
I think it would be more effort than it's worth for this repo.  People shouldn't have been linking to stuff under the `bwinton` github account.  But it's a good thing to keep in mind for the FirefoxUX version when we update it!
