### ISSUE TITLE
Don’t override any existing tables of contents.

### ISSUE THREAD

**Issue by bwinton** [bwinton/DesignSystem#57]
* Look for `<ul class="toc">` and if found, don't generate one.
* Also add `class="toc"` to the one we generate so that authors can style it if they want.

**Comment by aminalhazwani** [comment]
What if we use a custom component `<% ... %>` instead when we want to have a custom toc? For the styling we already do it here without a class https://github.com/bwinton/DesignSystem/blob/master/src/styles/page.scss#L23-L36

**Comment by aminalhazwani** [comment]
I added a custom component to the word list header https://bwinton.github.io/DesignSystem/word-list.html. We could check if the header has a custom component and if yes we should not generate the in-page toc.

**Comment by bwinton** [comment]
The custom component is replaced before it gets to the client, so you'll need to add a `class="toc"` to your custom component's `<ul>`.
