### ISSUE TITLE
[Request] Add a 'click to copy' colour feature and more colour previews to the Colors page

### ISSUE THREAD

**Issue by FatOrangutan** [bwinton/DesignSystem#71]
The previous style guide had a [nifty little feature](https://firefoxux.github.io/StyleGuide/#/colours) - click a colour to copy its hex code to the clipboard. In the new style guide, the hex code needs to be selected and then copied. A double click and a ctrl+c still takes longer than a single click :)

Also, please change the colour codes under 'Validations and notifications' to be inside boxes representing their colour, much like in the Palettes section.

**Comment by FatOrangutan** [comment]
Off-topic, but I'm not sure if I should open a new issue for this: the previous style guide had a [section](https://firefoxux.github.io/StyleGuide/#/icons) containing SVG's of all the icons used. Would something similar be added to this new guide too?

**Comment by brassy-** [comment]
@FatOrangutan quick answer to your off-topic: yes 👍 

General answer: we're going to have all the cool feature the StyleGuide had and even more! We just a need a bit of time ;)
