### ISSUE TITLE
page title should include page/section name

### ISSUE THREAD

**Issue by designakt** [bwinton/DesignSystem#74]
When looking for a previously visited DS page, I expect the page title to include the name of the page/section I had visited. 

![firefoxdesignsystempagetitle-back](https://cloud.githubusercontent.com/assets/8145891/25528888/1284daea-2c20-11e7-8ab6-eab779bce070.PNG)
![firefoxdesignsystempagetitle](https://cloud.githubusercontent.com/assets/8145891/25528705/5bae7d30-2c1f-11e7-84a1-9c2b4c059f70.PNG)

**Expected result:** each page follows this structure: 
_section name_ - _page name_ - category - Firefox Design System
_e.g. Export your icon - Iconography - Visual - Firefox Design System_

**Actual result:** all pages have the title "Firefox Design System"

**Comment by bwinton** [comment]
Since each section is in the same page, we can't have the section name be part of the title, but otherwise this seems doable…
