### ISSUE TITLE
Updates to punctuation guidelines

### ISSUE THREAD

**Issue by mheubusch** [bwinton/DesignSystem#85]
Let's discuss whether or not this change is necessary -it is an input following a bug https://bugzilla.mozilla.org/show_bug.cgi?id=1345515 - I can't tell if it even matters to specify this. 

Update this: Terminal Punctuation

Do not use punctuation at the end of a headline, button label, text link, or navigation element unless you are using an exclamation point or question mark or the link is embedded in running text. 

to this:

Terminal Punctuation

Do not use punctuation at the end of a headline, button label, text link, or navigation element unless you are using an exclamation point or question mark or the link is embedded in running text. Do not double space after periods.

**Comment by aminalhazwani** [comment]
In HTML multiple spaces will be rendered as one single space but we can still add this note. We are not aware of how other programming languages handle this and moreover we make it clear for people who may want to double space.
