### ISSUE TITLE
Allow subfolders in `/components` and rename it to `/includes`

### ISSUE THREAD

**Issue by aminalhazwani** [bwinton/DesignSystem#91]
The components folder is getting [pretty big](https://github.com/bwinton/DesignSystem/tree/colors-production/contents/components). Would be possible to have subfolders and maybe rename the folder from `/components` to `/includes`? Because we are going to have a 'components' chapter and it may create some confusion 😅

**Comment by bwinton** [comment]
I don't care what you name it, man…  😉

(Seriously, you can split up the html however you want, it should all work.  If you try something, and it doesn't work, push a branch and I'll take a look at what failed.)

**Comment by aminalhazwani** [comment]
Sorry, I thought it needed dev work to make it work.
