### ISSUE TITLE
Allow subfolders under /contents

### ISSUE THREAD

**Issue by aminalhazwani** [bwinton/DesignSystem#93]
In the `information-architecture-production`([here](https://github.com/bwinton/DesignSystem/tree/information-architecture-production)) branch I rearranged the contents in order to organize the `html` content files in different folders. The folder structure could be replicated as well in the url (i.e. http://bwinton.github.io/DesignSystem/motion/principles.html).

If a page has no subpages we could simply have a `index.html` inside the folder, see `resources/index.html`. Or should the `html` files be placed in the `/contents` folder in this case? 

In your opinion shall we continue to keep the includes `<% %>` under a `/includes` folder or with such a structure shall we place them inside the respective content folders?

Also the current deployed approach breaks the images. Should we add `..` to all `/images` link, right?

**Comment by bwinton** [comment]
The code is fixed on the branch, but I don't really have any opinions on the questions you asked, so I'm going to close this issue.  😉
