### ISSUE TITLE
Path of svg image for highliting external links

### ISSUE THREAD

**Issue by aminalhazwani** [bwinton/DesignSystem#99]
The path here https://github.com/bwinton/DesignSystem/blob/master/src/styles/page.scss#L140 should be `background-image: url('../images/global/open-new-tab.svg');` but if I add `..` to the path it fails the compilation locally.

**Comment by bwinton** [comment]
Fixed by whatever that last commit was.  😉
(urls need to be to the locations of the files on disk, so `../../images` in this case.)
